trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET 9 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

# Restore using SOLUTION file
- script: dotnet restore WebApplication1/WebApplication1.sln
  displayName: 'Restore'

# Build
- script: dotnet build WebApplication1/WebApplication1.sln \
    --configuration $(buildConfiguration) \
    --no-restore
  displayName: 'Build'

# Publish
- script: dotnet publish WebApplication1/WebApplication1.sln \
    --configuration $(buildConfiguration) \
    --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

# Publish artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
